### ISSUE TITLE
Can't vote on new item

### ISSUE THREAD

**Issue by beeblebrox** [spencewood/XboxApp#1]
Once I add a game it is added with 0 votes.  If I try to vote on it it reports that I can't vote on a game more than once a day.  Perhaps it is implying that since you added it then that counts as a vote?  If that is the case I'd expect it to register as being voted on once.

**Comment by spencewood** [comment]
Working as intended. The application allows the adding of one game OR making one vote per day. While I agree that a game added should come with an initial vote, this is not how the web service works.
